---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comp-value-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comp-value-admin
  template:
    metadata:
      labels:
        app: comp-value-admin
    spec:
      # 이미지 pull 토큰 설정 가져오기
      # kubectl create secret docker-registry ghcr-secret ...
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: my-container
          # (1) GHCR에서 가져올 이미지 주소
          image: ghcr.io/gnsgmlckdgk/comp-value-admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: comp-value-admin-service
spec:
  selector:
    app: comp-value-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # type을 NodePort나 LoadBalancer로 사용 가능. 
      # 예: NodePort = Node포트 할당, LoadBalancer = 클라우드 로드밸런서
  type: NodePort
