FROM node:18 AS build
WORKDIR /app

ENV REACT_APP_ENV=prod

COPY package*.json ./
RUN npm ci

COPY . .
COPY .env.prod .env
RUN npm run build

# ------------------------------------------------

FROM nginx:alpine
# 빌드 결과 복사
COPY --from=build /app/dist /usr/share/nginx/html

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# nginx 템플릿 + entrypoint 추가
# COPY docker/nginx.conf.template /etc/nginx/conf.d/default.conf.template
# COPY docker/entrypoint.sh /entrypoint.sh
# RUN chmod +x /entrypoint.sh

# CMD ["/entrypoint.sh"]

