FROM node:18 AS build
WORKDIR /app

# Yarn 레지스트리만 빠르게 설정 (기존 Yarn 사용)
RUN yarn config set registry https://registry.npmmirror.com

COPY package*.json ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]