name: Build and Push Docker Image to GHCR

env:
  REGISTRY: ghcr.io                       # 깃허브 컨테이너 저장소를 사용한다
  IMAGE_NAME: gnsgmlckdgk/comp-value-admin # 이미지의 이름. 자신의 깃허브 유저명을 소문자로 추가한다.
  VERSION: latest                         # 지금은 새 이미지를 latest로 태깅한다.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # (1) 깃 리포지토리 체크아웃
      - name: Check out repository code
        uses: actions/checkout@v3

      # (2) GHCR에 로그인
      # PAT로 GHCR에 로그인
      - name: Log in to GHCR using PAT
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      # 3) 도커 이미지 빌드
      #    - Dockerfile이 루트 경로에 있다고 가정
      #    - 만약 하위 디렉토리에 있다면 -f ./frontend/Dockerfile 처럼 경로를 바꿔줄 수 있음
      - name: Build Docker Image
        run:  docker build -f docker/DockerFile -t ghcr.io/gnsgmlckdgk/comp-value-admin:latest .

      # (4) GHCR로 push
      - name: Push Docker Image
        run: |
          docker push ${{env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{env.VERSION}}
